[project]
name = "perceptron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vipinyadavgit", email = "vipinyadav.git@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.0.0",
]

[project.scripts]
perceptron = "perceptron:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
